# Generated by Django 5.1.5 on 2025-01-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('Recipe', 'Recipe'), ('Diet', 'Diet'), ('Meditation', 'Meditation')], max_length=50)),
            ],
        ),
    ]
